apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: os
  template:
    metadata:
      name: os
      labels:
        app: os
    spec:
      containers:
      - name: nginx-container
        image: mero610/nginx-test
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "100Mi"
        ports:
          - containerPort: 80